# Generated by Django 5.0 on 2023-12-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
