# Generated by Django 5.0 on 2023-12-24 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(verbose_name='Дата оплаты')),
                ('amount_payment', models.PositiveIntegerField(blank='True', null='True', verbose_name='Сумма оплаты')),
                ('method_payment', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Перевод на счет')], max_length=20, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='study.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='study.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
