# Generated by Django 5.0 on 2024-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank='True', max_length=300, null='True', verbose_name='stripe_id'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_payment',
            field=models.PositiveIntegerField(verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(auto_now_add=True, null='True', verbose_name='Дата оплаты'),
        ),
    ]
